# Scan Docker image with trivy

on:
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: reactjs-image-gcp
jobs:
  build-and-push:
    runs-on: ubuntu-latest 
    environment: DOCKER_REPOSITORY
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v3
      - name: Use with SHA 
        run: | 
          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Show the TAGS values
        run: |
          echo "TAG value is : ${{ env.TAG }}"
      - name: Login to Docker Registry 
        run: |
          echo "${{ secrets.PASSWORD }}" | docker login -u ${{ secrets.USERNAME }} --password-stdin
      - name: Build Docker Image
        run: docker build -t ${{ secrets.USERNAME }}/${{env.IMAGE_NAME }}:${{ env.TAG }} .

      # - name: Scan the Docker Image with Trivy 
      #   id: trivy 
      #   uses: aquasecurity/trivy-action@v0.20.0
      #   with: 
      #     image-ref: ${{ secrets.USERNAME }}/${{env.IMAGE_NAME }}:${{ env.TAG }} 
      #     format: table 
      #     exit-code: 1 
      #     severity: CRITICAL,HIGH
      - name: Run Trivy scan and save report
        id: trivy
        run: |
          trivy image \
            --format json \
            --output trivy-report.json \
            --severity CRITICAL,HIGH \
            ${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:${{env.TAG}} || true

      # - name: Parse vulnerabilities
      #   id: parse
      #   run: |
      #     CRITICAL_COUNT=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="CRITICAL")] | length' trivy-report.json)
      #     HIGH_COUNT=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="HIGH")] | length' trivy-report.json)

      #     echo "CRITICAL=$CRITICAL_COUNT" >> $GITHUB_ENV
      #     echo "HIGH=$HIGH_COUNT" >> $GITHUB_ENV
      - name: Parse vulnerabilities
        run: |
          CRITICAL_COUNT=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="CRITICAL")] | length' trivy-report.json 2>/dev/null || echo 0)
          HIGH_COUNT=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="HIGH")] | length' trivy-report.json 2>/dev/null || echo 0)

          echo "CRITICAL=$CRITICAL_COUNT" >> $GITHUB_ENV
          echo "HIGH=$HIGH_COUNT" >> $GITHUB_ENV
      - name: Send Telegram Report
        if: env.CRITICAL != '0' || env.HIGH != '0'
        run: |
          MESSAGE="🚨 Docker Scan Failed\n\nCritical: $CRITICAL\nHigh: $HIGH\nImage: ${{ env.IMAGE_NAME }}:$TAG"

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MESSAGE"
      - name: Fail if vulnerabilities found
        if: env.CRITICAL != '0' || env.HIGH != '0'
        run: exit 1
      # - name: Send Telegram Alert if failed 
      #   if: failure() 
      #   run: |
      #     curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
      #     -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
      #     -d text="🚨 Docker Image Scan FAILED! Vulnerabilities detected."

      - name: Push the Docker image 
        if: success()
        run: |
          docker push ${{ secrets.USERNAME }}/${{env.IMAGE_NAME }}:${{ env.TAG }}
      - name: Logout from the Registry
        if: always()
        run: |
          docker logout 
  deploy-service: 
    needs: build-and-push
    if: success()
    runs-on: ubuntu-latest
    environment: GCP
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v3
      - name: Checking Result 
        run: |
          echo "Production on Deployment Works"
      # - name: Use with SHA 
      #   run: | 
      #     echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      # - name: Deploy via SSH to GCP VM 
      #   uses: appleboy/ssh-action@v1.0.0
      #   with: 
      #     host: ${{ secrets.GCP_IP }}
      #     username: ${{ secrets.GCP_USER }}
      #     key: ${{ secrets.GCP_PRIVATE_KEY }}
      #     envs: TAG
      #     script: |
      #       echo "Current location is $(pwd) "
            
      #       echo "remove the container "
      #       docker stop my-app || true 
      #       docker rm my-app || true 

      #       echo "Pulling the updating image "
      #       docker pull "69966/${{env.IMAGE_NAME }}:${{ env.TAG }}"

      #       echo "Running new containers "
      #       docker run -d \
      #         --name my-app \
      #         -p 3000:80 \
      #         "69966/${{env.IMAGE_NAME }}:${{ env.TAG }}"
            
  
